### PR TITLE
Make use of check method instead of user

### PR DESCRIPTION
**Pull request by mercuryseries**
Since we're just checking I think it's more readable

### CODE REVIEW

**Comment by freekmurze** [comment]
Why did you close this? Seemed like a good change...

**Comment by mercuryseries** [comment]
And this PR is back again :)

**Comment by freekmurze** [comment]
Cool! Could you let the function return the result of `auth()->check()`? Then we don't need that if statement anymore.

**Comment by mercuryseries** [comment]
Nice one! I compacted it with the OR operator.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
